title: For Information Security
author: hackintoanetwork
email: hackintoanetwork@gmail.com
description: > 
  hackintoanetwork
show_excerpts: true
baseurl: 


sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: hackintoanetwork
  tagline: Security Lab
  date_format: "%b %-d, %Y"
  remote_theme: samarsault/texture
  theme: texture
  style: black
  showPicker: false
  analytics_id: '198541497'
  show_excerpts: true
  showNav: true



  social_links:
    twitter: hackintoanetwo1
    github:  hackintoanetwork
    instagram: hackintoanetwork
    rss: rss
 


plugins:
  - jekyll-seo-tag

