title: For Information Security
author: hackintoanetwork
email: hackintoanetwork@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  hackintoanetwork
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: 


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: hackintoanetwork
  tagline: Developer. Hacker
  date_format: "%b %-d, %Y"
  remote_theme: samarsault/texture
  theme: texture
  style: black
  showPicker: false
  show_excerpts: true
  showNav: true
  navigation:
  - title: Home
    url: "/"
  - title: Posts
    url: "/posts"

  

  # generate social links in footer
  social_links:
    twitter: hackintoanetwo1
    github:  hackintoanetwork
    instagram: hackintoanetwork
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
